version: '3.8'
networks:
    webapp:
services:
    nginx_logistik:
        image: nginx:alpine
        container_name: nginx_logistik
        ports:
            - "8098:8098"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
        depends_on:
            - logistik
            - db_logistik
        networks:
            - webapp

    db_logistik:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'logistik'
            MYSQL_USER: 'dimas'
            MYSQL_PASSWORD: 'dimas1950'
            MYSQL_ROOT_PASSWORD: 'dimas1950'
        ports:
            - '3306:3306'
        networks:
            - webapp

    logistik:
        container_name: logistik
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        networks:
            - webapp

    #phpMyAdmin Service
    # phpmyadmin:
    #   image: phpmyadmin/phpmyadmin
    #   container_name: phpmyadmin
    #   ports:
    #     - "3400:80"
    #   depends_on:
    #     - db


    # pgadmin:
    #     image: dpage/pgadmin4
    #     container_name: pgAdmin
    #     ports:
    #         - "5050:80"
    #     depends_on:
    #         - db
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: hanieasemi76@gmail.com
    #         PGADMIN_DEFAULT_PASSWORD: password
